### ISSUE TITLE
Current Gmock generates a lot of warning on Ubuntu 22.04 with Clang

### ISSUE THREAD

**Issue by JvE-Lely** [ament/googletest#23]
On Humble building unittests generated a lot of warning with regard to GMock:
```
In file included from /opt/ros/humble/src/gmock_vendor/include/gmock/gmock-spec-builders.h:75:
/opt/ros/humble/src/gmock_vendor/include/gmock/gmock-matchers.h:721:3: warning: definition of implicit copy constructor for 'StrEqualityMatcher<std::basic_string<char>>' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy]
  GTEST_DISALLOW_ASSIGN_(StrEqualityMatcher);
```
Can this be fixed since it generates a lot warning making it impossible to find the error.

In GMock this is fixed in https://github.com/google/googletest/pull/2815

**Comment by clalancette** [comment]
Can you give us an example of how you are using this?  If you use gmock as a modern CMake target, CMake will automatically mark these headers as SYSTEM and thus suppress the warnings.
