### ISSUE TITLE
gtest:return code -11

### ISSUE THREAD

**Issue by RachelRen05** [ament/googletest#7]
when I use **colcon test** to run test, an error occurred:
`[       OK ]
 [  PASSED  ] 1 test.
 -- run_test.py: return code -11`

What puzzles me is that the result of test passed, but why the return value of RUN_ALL_TESTS is **-11**?  What does this return value represent?
Thanks very much.

**Comment by dirk-thomas** [comment]
Your test executable crashed with a segmentation fault.

I will close the ticket since there is nothing to be done in this repo.
